# Generated by Django 5.2.5 on 2025-09-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_warehouse_keeper',
            field=models.BooleanField(default=False),
        ),
    ]
